### ISSUE TITLE
Mcrypt

### ISSUE THREAD

**Issue by jonathanstanley** [GoogleCloudPlatform/laravel#2]
Had trouble during `composer install` on my mac.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for laravel/framework v5.0.16 -> satisfiable by laravel/framework[v5.0.16].
    - laravel/framework v5.0.16 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
```

Before getting to this step I had also received a white screen of death after following the standard `composer create-project laravel/laravel` I couldn't get any php errors to help hunt down the problem.  The GAE Launcher log simply threw a 500 error and described a mail error of some sort.

Apparently these problems arise because Apple doesn't include mcrypt by default.  There is no mention of this in the [readme](https://github.com/GoogleCloudPlatform/laravel/blob/5.0.22/readme.md#troubleshooting).  (It would be nice if there was a mention)

If it helps others, the easiest way I found to run Laravel through Google App Engine (Launcher) on Mac Yosemite is to 
1. Get mcrypt installed - http://jacurtis.com/easily-install-mcrypt-php-mavericks-yosemite/
2. Follow install instructions - https://github.com/GoogleCloudPlatform/laravel/

**Comment by marslangoog** [comment]
The GAE Mac SDK comes with a built-in PHP interpreter that has the mcrypt extension. It will be used by default if the "--php_executable_path" flag is not specified.

**Comment by jonathanstanley** [comment]
Sorry for the late response @marslangoog 

I'm not sure if we're talking about the same thing.  This error occurs when I run `composer install`... not to do with the SDK.  In any case I added the following [cask](https://github.com/caskroom/homebrew-cask) / [homebrew](https://github.com/Homebrew/homebrew) to my .osx [dotfile](https://github.com/mathiasbynens/dotfiles/blob/master/.osx) to make it simpler to get moving:

``` sh
brew cask install googleappengine
brew install mcrypt #required for laravel
brew install php56-mcrypt #required for laravel
```
